### ISSUE TITLE
Conflicting color issue between default bare text/prompt and user's terminal presets

### ISSUE THREAD

**Issue by leerobertdyer** [GroveOS/bare.sh#2]
There is a current issue where the text may not be readable depending on what presets the user has set up on their own terminal.

As a user I'd like to be able to read the initial message from bare so that I know how to exit, and can read my prompt.

**Comment by matthewlarkin** [comment]
Nice spot!

I've added a `BARE_COLOR` env variable option. It can be set in `.etc/barerc`.

This way, bare will be colorless unless you set BARE_COLOR=1, then you'll have colors in your terminal 👍
