### ISSUE TITLE
Difficult to establish openai chat response from rest of terminal

### ISSUE THREAD

**Issue by leerobertdyer** [GroveOS/bare.sh#3]
As a user, I'd like to have the lines of response from ```openai chat```  separated from the rest of my terminal lines so that I may easily locate my question and the responses.

<img width="1397" alt="Screen Shot 2024-08-09 at 10 12 32 PM" src="https://github.com/user-attachments/assets/01a7015f-9371-4a55-9857-bba368360b58">

**Comment by matthewlarkin** [comment]
Ah yes, you mean something like this

```terminal
bare.sh > openai chat "hi there"

Hi there, how can I assist today?
```

as opposed to this?

```terminal
bare.sh > openai chat "hi there"
Hi there, how can I assist today?
```

I believe the ideal format for programs downstream is clean (non prettified) output. Better for pipelines and interoperability between tools, I think. For instance, pretty output might cause unexpected double padding here.

```bash
poem_markup=$(openai chat "write a poem" | render --to-html)

html="<p>Here is a poem</p>$poem_markup"
```

That said, I think an `ENV` variable or inline `--pretty` flag could help in your usecase.

- - -

in the meantime, you may also consider terminal extensions that can help with readability. I believe zsh has plugins to help. In bash, I use [ble.sh](https://github.com/akinomyoga/ble.sh), which syntax highlights the terminal like a bash script:

![bare-random--with-lowercase](https://github.com/user-attachments/assets/799ecbd8-ba6a-4e3d-9580-41144ed3bcb0)

**Comment by matthewlarkin** [comment]
Hey @leerobertdyer, following up here, we now have the `pretty` command 🚀 which can take stdin and make it pretty.

For this you'll need the `glow` package (installable via homebrew on Mac or snap/apt-get on Ubuntu).

Then, simply pipe any content to `pretty` and it'll render like so:

```console
echo "Hi there" | pretty

    Hi there  

```

Works especially well with markdown content. Here's a visual:

![pretty](https://github.com/user-attachments/assets/eb7c8037-14ad-4010-8d23-dfcdfa338c91)

- - -

Fun fact, the original screenshot here was in webp format, but GitHub doesn't allow webp (🤷‍♂️), so I converted it to jpg with bare:

```
image convert pretty.webp pretty.jpg
```

**Comment by matthewlarkin** [comment]
By the way, bare had a significant update a few days ago, simplifying the codebase to a few files.

You may not need it, but there a migration script in `upgrades.md`. Otherwise, most things should still work just the same as they were.

If you had `bare` aliased to the old `bare.sh/bare` file, you'll need to update that in your ~/.bashrc (or similar) file, like so:

```bash
alias bare="$HOME/bare.sh/bare.sh" # assuming bare.sh is in your home directory
```

**Comment by leerobertdyer** [comment]
This is awesome! I'll have to take a peek behind the curtain when I get more time but thanks for adding this :)


> Hey @leerobertdyer, following up here, we now have the `pretty` command 🚀 which can take stdin and make it pretty.
> 
> For this you'll need the `glow` package (installable via homebrew on Mac or snap/apt-get on Ubuntu).
> 
> Then, simply pipe any content to `pretty` and it'll render like so:
> 
> ```
> echo "Hi there" | pretty
> 
>     Hi there  
> ```
> 
> Works especially well with markdown content. Here's a visual:
> 
> ![pretty](https://private-user-images.githubusercontent.com/64444745/361916389-eb7c8037-14ad-4010-8d23-dfcdfa338c91.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDYwOTEsIm5iZiI6MTcyNDgwNTc5MSwicGF0aCI6Ii82NDQ0NDc0NS8zNjE5MTYzODktZWI3YzgwMzctMTRhZC00MDEwLThkMjMtZGZjZGZhMzM4YzkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAwNDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMjM1ODc5ZTRkMjY4Nzg5YTgzODNiY2FjZTE2NWI1ZGU2NjI4NjNlYTY1YjJiMWQxMzFjMDUwY2EwNTBiOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ySAtd_4dwjMtdwGDzu3_5Opu7SuDk-C-qO3Z70sMLyE)
> 
> Fun fact, the original screenshot here was in webp format, but GitHub doesn't allow webp (🤷‍♂️), so I converted it to jpg with bare:
> 
> ```
> image convert pretty.webp pretty.jpg
> ```
